# Types de flux
TYPES_FLUX   = ['ENTRANT', 'SORTANT']
STATUTS_FLUX = ['PLANIFIE', 'EN_COURS', 'REALISE']

# Statuts de flux
STATUT_PLANIFIE  = 'PLANIFIE'
STATUT_EN_COURS  = 'EN_COURS'
STATUT_REALISE   = 'REALISE'

TYPES_FLUX   = ['ENTRANT', 'SORTANT']
STATUTS_FLUX = ['PLANIFIE', 'EN_COURS', 'REALISE']

# Horizons par défaut
DEFAULT_HORIZON_JOURS = 90
DEFAULT_COURBE_JOURS  = 60